//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.2.0
//     from Assets/System/InputHandler/InputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputActions : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputActions"",
    ""maps"": [
        {
            ""name"": ""InputPlayer"",
            ""id"": ""d5fd7595-0b76-4923-80cb-406b9ca500cb"",
            ""actions"": [
                {
                    ""name"": ""PlayerMovement"",
                    ""type"": ""Value"",
                    ""id"": ""6f624a1d-5bd2-4f1a-a0c7-9a9cccd53d9b"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""PrimaryAction"",
                    ""type"": ""Button"",
                    ""id"": ""bad79abc-5342-4693-9f33-2591b4c7894b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SecondaryAction"",
                    ""type"": ""Button"",
                    ""id"": ""62ec00aa-f388-45f8-92dc-fdb26e8fb1e6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Hotbar1"",
                    ""type"": ""Button"",
                    ""id"": ""1f2cecdf-abcc-4e90-937e-de8bd6e66dba"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Hotbar2"",
                    ""type"": ""Button"",
                    ""id"": ""1166b27b-3b16-4543-b7cd-045b04520c94"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Hotbar3"",
                    ""type"": ""Button"",
                    ""id"": ""27c621a8-ec46-4fc8-9963-762db3ff65e0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Hotbar4"",
                    ""type"": ""Button"",
                    ""id"": ""92960273-a674-459f-8821-f55898f68be2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Hotbar5"",
                    ""type"": ""Button"",
                    ""id"": ""5a5c0a0e-623d-4483-ba4c-de25a3055e63"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Hotbar6"",
                    ""type"": ""Button"",
                    ""id"": ""532192ef-f7e0-40f7-9e9a-f934525e85b2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Hotbar7"",
                    ""type"": ""Button"",
                    ""id"": ""b0c3daa2-b3ca-4f5e-a0ec-93207762f6a1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Hotbar8"",
                    ""type"": ""Button"",
                    ""id"": ""8581424b-b376-4e45-b8ac-7c7efdaf6e46"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""0babd016-35da-4a01-9966-65bce4b8118e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""OpenInventory"",
                    ""type"": ""Button"",
                    ""id"": ""4c6f0692-1943-42ba-beec-4c1bab2e27cb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""OpenMenuFromPlayer"",
                    ""type"": ""Button"",
                    ""id"": ""62d7e6c2-d86c-486f-b7c3-674fb543f746"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""fe263e4e-87ec-42c4-b965-2016b3a5fa99"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayerMovement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""b109ba85-8f3a-484c-bf5e-58ab8cba1b2b"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayerMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""a30b25a9-88ce-4cd9-b124-022eb0c77df1"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayerMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""a029734f-e133-426c-a153-25872016a49e"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayerMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""8aa783bc-265c-4e88-951e-cab1f5ac57c7"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayerMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""451efecd-03d1-41b2-b052-9fa1db24ffbf"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PrimaryAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3afe1f90-11f6-4ae7-b936-d794f88eaf5f"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SecondaryAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""44817782-3cd3-401c-9040-e4eedcd4b0b4"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Hotbar1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""65107e62-7d56-4e3f-a5ef-7c9ff414c5e9"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Hotbar2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""165674a8-ce7f-4f26-a533-1355aa99757a"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Hotbar3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""acbacfcc-2d51-4a6a-a1fd-997967f5dcbb"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Hotbar4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b850b15a-b558-4244-be17-ea8e4986b22d"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenInventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e772f3c4-03d9-477e-96b3-a4943d948b21"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""eb5e26fc-f3ad-4d6f-9d57-c6155429b74c"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenMenuFromPlayer"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ed21fa3b-920a-4930-9b21-a7b013f1bb65"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Hotbar5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""16f7ab0c-d32d-4338-9431-2098b39b7d77"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Hotbar6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5f30219f-eb41-49e8-8ba8-1da4fa14fe72"",
                    ""path"": ""<Keyboard>/7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Hotbar7"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""648ebd19-679d-4852-9cfe-4d226892d14e"",
                    ""path"": ""<Keyboard>/8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Hotbar8"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""InputMenu"",
            ""id"": ""c34761d0-b08d-4dfe-b002-3cded206a8d8"",
            ""actions"": [
                {
                    ""name"": ""MenuMovement"",
                    ""type"": ""Value"",
                    ""id"": ""b4fda01e-e7d2-42d2-ba43-436b416d2b6e"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""LeftClickMenu"",
                    ""type"": ""Button"",
                    ""id"": ""73ae2149-34b9-48ae-ab56-84c3d8a5c0e9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightClickMenu"",
                    ""type"": ""Button"",
                    ""id"": ""b2c266b3-f8f4-41aa-a4c0-0f15c56ce0a1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CloseMenu"",
                    ""type"": ""Button"",
                    ""id"": ""51c0929e-515a-4d1d-bee1-49dc309e0c26"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""2c2806ef-c13a-48a8-b382-0703caf12f5c"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MenuMovement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""daaeef36-48ab-4730-81c0-0c5761121291"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MenuMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""ebbfd62d-42fd-46b9-8694-3f7e248f96ca"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MenuMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""f84cab05-8cb6-44e0-a806-7caf9f53732f"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MenuMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""698282f0-bf4b-419b-a9c1-220e8d840a7a"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MenuMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""932a9d5f-6a95-4193-8fcb-a31852d4b65d"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftClickMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""41a176dd-9ff3-49df-8e99-8cf68019a757"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightClickMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f0964c15-6fbe-4c20-beb9-e74b8773ddd7"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CloseMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""InputUI"",
            ""id"": ""be9c115e-d043-4dfc-94e5-c8f5a9f52b22"",
            ""actions"": [
                {
                    ""name"": ""CloseInventory"",
                    ""type"": ""Button"",
                    ""id"": ""f867775f-1151-4c38-9328-9eba2602576a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""EButton"",
                    ""type"": ""Button"",
                    ""id"": ""a3f78e5e-e2e6-4669-b836-b28dbbbdae6f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftClickUI"",
                    ""type"": ""Button"",
                    ""id"": ""91b546f3-f2ee-49b7-84ee-14ff44db6727"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightClickUI"",
                    ""type"": ""Button"",
                    ""id"": ""f34db38a-1eb4-4b8c-a15d-0a2203f8989f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""OpenMenuFromUI"",
                    ""type"": ""Button"",
                    ""id"": ""0e59e03d-896a-49f3-9c3e-2af28ca7ced4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""7e73680f-d4ba-433a-9ad6-bda3d679f861"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CloseInventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bc24cc96-543a-40ad-9d6a-17a4b334f787"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""EButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""648ed43f-374a-48f2-ab8b-42f1ea11f3ae"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightClickUI"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5d31561b-a1f6-48fa-a581-2094ff4f9ad3"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftClickUI"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7075fbba-ceb1-48d2-bfa3-280d8983e84a"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenMenuFromUI"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""New control scheme"",
            ""bindingGroup"": ""New control scheme"",
            ""devices"": [
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // InputPlayer
        m_InputPlayer = asset.FindActionMap("InputPlayer", throwIfNotFound: true);
        m_InputPlayer_PlayerMovement = m_InputPlayer.FindAction("PlayerMovement", throwIfNotFound: true);
        m_InputPlayer_PrimaryAction = m_InputPlayer.FindAction("PrimaryAction", throwIfNotFound: true);
        m_InputPlayer_SecondaryAction = m_InputPlayer.FindAction("SecondaryAction", throwIfNotFound: true);
        m_InputPlayer_Hotbar1 = m_InputPlayer.FindAction("Hotbar1", throwIfNotFound: true);
        m_InputPlayer_Hotbar2 = m_InputPlayer.FindAction("Hotbar2", throwIfNotFound: true);
        m_InputPlayer_Hotbar3 = m_InputPlayer.FindAction("Hotbar3", throwIfNotFound: true);
        m_InputPlayer_Hotbar4 = m_InputPlayer.FindAction("Hotbar4", throwIfNotFound: true);
        m_InputPlayer_Hotbar5 = m_InputPlayer.FindAction("Hotbar5", throwIfNotFound: true);
        m_InputPlayer_Hotbar6 = m_InputPlayer.FindAction("Hotbar6", throwIfNotFound: true);
        m_InputPlayer_Hotbar7 = m_InputPlayer.FindAction("Hotbar7", throwIfNotFound: true);
        m_InputPlayer_Hotbar8 = m_InputPlayer.FindAction("Hotbar8", throwIfNotFound: true);
        m_InputPlayer_Interact = m_InputPlayer.FindAction("Interact", throwIfNotFound: true);
        m_InputPlayer_OpenInventory = m_InputPlayer.FindAction("OpenInventory", throwIfNotFound: true);
        m_InputPlayer_OpenMenuFromPlayer = m_InputPlayer.FindAction("OpenMenuFromPlayer", throwIfNotFound: true);
        // InputMenu
        m_InputMenu = asset.FindActionMap("InputMenu", throwIfNotFound: true);
        m_InputMenu_MenuMovement = m_InputMenu.FindAction("MenuMovement", throwIfNotFound: true);
        m_InputMenu_LeftClickMenu = m_InputMenu.FindAction("LeftClickMenu", throwIfNotFound: true);
        m_InputMenu_RightClickMenu = m_InputMenu.FindAction("RightClickMenu", throwIfNotFound: true);
        m_InputMenu_CloseMenu = m_InputMenu.FindAction("CloseMenu", throwIfNotFound: true);
        // InputUI
        m_InputUI = asset.FindActionMap("InputUI", throwIfNotFound: true);
        m_InputUI_CloseInventory = m_InputUI.FindAction("CloseInventory", throwIfNotFound: true);
        m_InputUI_EButton = m_InputUI.FindAction("EButton", throwIfNotFound: true);
        m_InputUI_LeftClickUI = m_InputUI.FindAction("LeftClickUI", throwIfNotFound: true);
        m_InputUI_RightClickUI = m_InputUI.FindAction("RightClickUI", throwIfNotFound: true);
        m_InputUI_OpenMenuFromUI = m_InputUI.FindAction("OpenMenuFromUI", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // InputPlayer
    private readonly InputActionMap m_InputPlayer;
    private IInputPlayerActions m_InputPlayerActionsCallbackInterface;
    private readonly InputAction m_InputPlayer_PlayerMovement;
    private readonly InputAction m_InputPlayer_PrimaryAction;
    private readonly InputAction m_InputPlayer_SecondaryAction;
    private readonly InputAction m_InputPlayer_Hotbar1;
    private readonly InputAction m_InputPlayer_Hotbar2;
    private readonly InputAction m_InputPlayer_Hotbar3;
    private readonly InputAction m_InputPlayer_Hotbar4;
    private readonly InputAction m_InputPlayer_Hotbar5;
    private readonly InputAction m_InputPlayer_Hotbar6;
    private readonly InputAction m_InputPlayer_Hotbar7;
    private readonly InputAction m_InputPlayer_Hotbar8;
    private readonly InputAction m_InputPlayer_Interact;
    private readonly InputAction m_InputPlayer_OpenInventory;
    private readonly InputAction m_InputPlayer_OpenMenuFromPlayer;
    public struct InputPlayerActions
    {
        private @InputActions m_Wrapper;
        public InputPlayerActions(@InputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @PlayerMovement => m_Wrapper.m_InputPlayer_PlayerMovement;
        public InputAction @PrimaryAction => m_Wrapper.m_InputPlayer_PrimaryAction;
        public InputAction @SecondaryAction => m_Wrapper.m_InputPlayer_SecondaryAction;
        public InputAction @Hotbar1 => m_Wrapper.m_InputPlayer_Hotbar1;
        public InputAction @Hotbar2 => m_Wrapper.m_InputPlayer_Hotbar2;
        public InputAction @Hotbar3 => m_Wrapper.m_InputPlayer_Hotbar3;
        public InputAction @Hotbar4 => m_Wrapper.m_InputPlayer_Hotbar4;
        public InputAction @Hotbar5 => m_Wrapper.m_InputPlayer_Hotbar5;
        public InputAction @Hotbar6 => m_Wrapper.m_InputPlayer_Hotbar6;
        public InputAction @Hotbar7 => m_Wrapper.m_InputPlayer_Hotbar7;
        public InputAction @Hotbar8 => m_Wrapper.m_InputPlayer_Hotbar8;
        public InputAction @Interact => m_Wrapper.m_InputPlayer_Interact;
        public InputAction @OpenInventory => m_Wrapper.m_InputPlayer_OpenInventory;
        public InputAction @OpenMenuFromPlayer => m_Wrapper.m_InputPlayer_OpenMenuFromPlayer;
        public InputActionMap Get() { return m_Wrapper.m_InputPlayer; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(InputPlayerActions set) { return set.Get(); }
        public void SetCallbacks(IInputPlayerActions instance)
        {
            if (m_Wrapper.m_InputPlayerActionsCallbackInterface != null)
            {
                @PlayerMovement.started -= m_Wrapper.m_InputPlayerActionsCallbackInterface.OnPlayerMovement;
                @PlayerMovement.performed -= m_Wrapper.m_InputPlayerActionsCallbackInterface.OnPlayerMovement;
                @PlayerMovement.canceled -= m_Wrapper.m_InputPlayerActionsCallbackInterface.OnPlayerMovement;
                @PrimaryAction.started -= m_Wrapper.m_InputPlayerActionsCallbackInterface.OnPrimaryAction;
                @PrimaryAction.performed -= m_Wrapper.m_InputPlayerActionsCallbackInterface.OnPrimaryAction;
                @PrimaryAction.canceled -= m_Wrapper.m_InputPlayerActionsCallbackInterface.OnPrimaryAction;
                @SecondaryAction.started -= m_Wrapper.m_InputPlayerActionsCallbackInterface.OnSecondaryAction;
                @SecondaryAction.performed -= m_Wrapper.m_InputPlayerActionsCallbackInterface.OnSecondaryAction;
                @SecondaryAction.canceled -= m_Wrapper.m_InputPlayerActionsCallbackInterface.OnSecondaryAction;
                @Hotbar1.started -= m_Wrapper.m_InputPlayerActionsCallbackInterface.OnHotbar1;
                @Hotbar1.performed -= m_Wrapper.m_InputPlayerActionsCallbackInterface.OnHotbar1;
                @Hotbar1.canceled -= m_Wrapper.m_InputPlayerActionsCallbackInterface.OnHotbar1;
                @Hotbar2.started -= m_Wrapper.m_InputPlayerActionsCallbackInterface.OnHotbar2;
                @Hotbar2.performed -= m_Wrapper.m_InputPlayerActionsCallbackInterface.OnHotbar2;
                @Hotbar2.canceled -= m_Wrapper.m_InputPlayerActionsCallbackInterface.OnHotbar2;
                @Hotbar3.started -= m_Wrapper.m_InputPlayerActionsCallbackInterface.OnHotbar3;
                @Hotbar3.performed -= m_Wrapper.m_InputPlayerActionsCallbackInterface.OnHotbar3;
                @Hotbar3.canceled -= m_Wrapper.m_InputPlayerActionsCallbackInterface.OnHotbar3;
                @Hotbar4.started -= m_Wrapper.m_InputPlayerActionsCallbackInterface.OnHotbar4;
                @Hotbar4.performed -= m_Wrapper.m_InputPlayerActionsCallbackInterface.OnHotbar4;
                @Hotbar4.canceled -= m_Wrapper.m_InputPlayerActionsCallbackInterface.OnHotbar4;
                @Hotbar5.started -= m_Wrapper.m_InputPlayerActionsCallbackInterface.OnHotbar5;
                @Hotbar5.performed -= m_Wrapper.m_InputPlayerActionsCallbackInterface.OnHotbar5;
                @Hotbar5.canceled -= m_Wrapper.m_InputPlayerActionsCallbackInterface.OnHotbar5;
                @Hotbar6.started -= m_Wrapper.m_InputPlayerActionsCallbackInterface.OnHotbar6;
                @Hotbar6.performed -= m_Wrapper.m_InputPlayerActionsCallbackInterface.OnHotbar6;
                @Hotbar6.canceled -= m_Wrapper.m_InputPlayerActionsCallbackInterface.OnHotbar6;
                @Hotbar7.started -= m_Wrapper.m_InputPlayerActionsCallbackInterface.OnHotbar7;
                @Hotbar7.performed -= m_Wrapper.m_InputPlayerActionsCallbackInterface.OnHotbar7;
                @Hotbar7.canceled -= m_Wrapper.m_InputPlayerActionsCallbackInterface.OnHotbar7;
                @Hotbar8.started -= m_Wrapper.m_InputPlayerActionsCallbackInterface.OnHotbar8;
                @Hotbar8.performed -= m_Wrapper.m_InputPlayerActionsCallbackInterface.OnHotbar8;
                @Hotbar8.canceled -= m_Wrapper.m_InputPlayerActionsCallbackInterface.OnHotbar8;
                @Interact.started -= m_Wrapper.m_InputPlayerActionsCallbackInterface.OnInteract;
                @Interact.performed -= m_Wrapper.m_InputPlayerActionsCallbackInterface.OnInteract;
                @Interact.canceled -= m_Wrapper.m_InputPlayerActionsCallbackInterface.OnInteract;
                @OpenInventory.started -= m_Wrapper.m_InputPlayerActionsCallbackInterface.OnOpenInventory;
                @OpenInventory.performed -= m_Wrapper.m_InputPlayerActionsCallbackInterface.OnOpenInventory;
                @OpenInventory.canceled -= m_Wrapper.m_InputPlayerActionsCallbackInterface.OnOpenInventory;
                @OpenMenuFromPlayer.started -= m_Wrapper.m_InputPlayerActionsCallbackInterface.OnOpenMenuFromPlayer;
                @OpenMenuFromPlayer.performed -= m_Wrapper.m_InputPlayerActionsCallbackInterface.OnOpenMenuFromPlayer;
                @OpenMenuFromPlayer.canceled -= m_Wrapper.m_InputPlayerActionsCallbackInterface.OnOpenMenuFromPlayer;
            }
            m_Wrapper.m_InputPlayerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @PlayerMovement.started += instance.OnPlayerMovement;
                @PlayerMovement.performed += instance.OnPlayerMovement;
                @PlayerMovement.canceled += instance.OnPlayerMovement;
                @PrimaryAction.started += instance.OnPrimaryAction;
                @PrimaryAction.performed += instance.OnPrimaryAction;
                @PrimaryAction.canceled += instance.OnPrimaryAction;
                @SecondaryAction.started += instance.OnSecondaryAction;
                @SecondaryAction.performed += instance.OnSecondaryAction;
                @SecondaryAction.canceled += instance.OnSecondaryAction;
                @Hotbar1.started += instance.OnHotbar1;
                @Hotbar1.performed += instance.OnHotbar1;
                @Hotbar1.canceled += instance.OnHotbar1;
                @Hotbar2.started += instance.OnHotbar2;
                @Hotbar2.performed += instance.OnHotbar2;
                @Hotbar2.canceled += instance.OnHotbar2;
                @Hotbar3.started += instance.OnHotbar3;
                @Hotbar3.performed += instance.OnHotbar3;
                @Hotbar3.canceled += instance.OnHotbar3;
                @Hotbar4.started += instance.OnHotbar4;
                @Hotbar4.performed += instance.OnHotbar4;
                @Hotbar4.canceled += instance.OnHotbar4;
                @Hotbar5.started += instance.OnHotbar5;
                @Hotbar5.performed += instance.OnHotbar5;
                @Hotbar5.canceled += instance.OnHotbar5;
                @Hotbar6.started += instance.OnHotbar6;
                @Hotbar6.performed += instance.OnHotbar6;
                @Hotbar6.canceled += instance.OnHotbar6;
                @Hotbar7.started += instance.OnHotbar7;
                @Hotbar7.performed += instance.OnHotbar7;
                @Hotbar7.canceled += instance.OnHotbar7;
                @Hotbar8.started += instance.OnHotbar8;
                @Hotbar8.performed += instance.OnHotbar8;
                @Hotbar8.canceled += instance.OnHotbar8;
                @Interact.started += instance.OnInteract;
                @Interact.performed += instance.OnInteract;
                @Interact.canceled += instance.OnInteract;
                @OpenInventory.started += instance.OnOpenInventory;
                @OpenInventory.performed += instance.OnOpenInventory;
                @OpenInventory.canceled += instance.OnOpenInventory;
                @OpenMenuFromPlayer.started += instance.OnOpenMenuFromPlayer;
                @OpenMenuFromPlayer.performed += instance.OnOpenMenuFromPlayer;
                @OpenMenuFromPlayer.canceled += instance.OnOpenMenuFromPlayer;
            }
        }
    }
    public InputPlayerActions @InputPlayer => new InputPlayerActions(this);

    // InputMenu
    private readonly InputActionMap m_InputMenu;
    private IInputMenuActions m_InputMenuActionsCallbackInterface;
    private readonly InputAction m_InputMenu_MenuMovement;
    private readonly InputAction m_InputMenu_LeftClickMenu;
    private readonly InputAction m_InputMenu_RightClickMenu;
    private readonly InputAction m_InputMenu_CloseMenu;
    public struct InputMenuActions
    {
        private @InputActions m_Wrapper;
        public InputMenuActions(@InputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @MenuMovement => m_Wrapper.m_InputMenu_MenuMovement;
        public InputAction @LeftClickMenu => m_Wrapper.m_InputMenu_LeftClickMenu;
        public InputAction @RightClickMenu => m_Wrapper.m_InputMenu_RightClickMenu;
        public InputAction @CloseMenu => m_Wrapper.m_InputMenu_CloseMenu;
        public InputActionMap Get() { return m_Wrapper.m_InputMenu; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(InputMenuActions set) { return set.Get(); }
        public void SetCallbacks(IInputMenuActions instance)
        {
            if (m_Wrapper.m_InputMenuActionsCallbackInterface != null)
            {
                @MenuMovement.started -= m_Wrapper.m_InputMenuActionsCallbackInterface.OnMenuMovement;
                @MenuMovement.performed -= m_Wrapper.m_InputMenuActionsCallbackInterface.OnMenuMovement;
                @MenuMovement.canceled -= m_Wrapper.m_InputMenuActionsCallbackInterface.OnMenuMovement;
                @LeftClickMenu.started -= m_Wrapper.m_InputMenuActionsCallbackInterface.OnLeftClickMenu;
                @LeftClickMenu.performed -= m_Wrapper.m_InputMenuActionsCallbackInterface.OnLeftClickMenu;
                @LeftClickMenu.canceled -= m_Wrapper.m_InputMenuActionsCallbackInterface.OnLeftClickMenu;
                @RightClickMenu.started -= m_Wrapper.m_InputMenuActionsCallbackInterface.OnRightClickMenu;
                @RightClickMenu.performed -= m_Wrapper.m_InputMenuActionsCallbackInterface.OnRightClickMenu;
                @RightClickMenu.canceled -= m_Wrapper.m_InputMenuActionsCallbackInterface.OnRightClickMenu;
                @CloseMenu.started -= m_Wrapper.m_InputMenuActionsCallbackInterface.OnCloseMenu;
                @CloseMenu.performed -= m_Wrapper.m_InputMenuActionsCallbackInterface.OnCloseMenu;
                @CloseMenu.canceled -= m_Wrapper.m_InputMenuActionsCallbackInterface.OnCloseMenu;
            }
            m_Wrapper.m_InputMenuActionsCallbackInterface = instance;
            if (instance != null)
            {
                @MenuMovement.started += instance.OnMenuMovement;
                @MenuMovement.performed += instance.OnMenuMovement;
                @MenuMovement.canceled += instance.OnMenuMovement;
                @LeftClickMenu.started += instance.OnLeftClickMenu;
                @LeftClickMenu.performed += instance.OnLeftClickMenu;
                @LeftClickMenu.canceled += instance.OnLeftClickMenu;
                @RightClickMenu.started += instance.OnRightClickMenu;
                @RightClickMenu.performed += instance.OnRightClickMenu;
                @RightClickMenu.canceled += instance.OnRightClickMenu;
                @CloseMenu.started += instance.OnCloseMenu;
                @CloseMenu.performed += instance.OnCloseMenu;
                @CloseMenu.canceled += instance.OnCloseMenu;
            }
        }
    }
    public InputMenuActions @InputMenu => new InputMenuActions(this);

    // InputUI
    private readonly InputActionMap m_InputUI;
    private IInputUIActions m_InputUIActionsCallbackInterface;
    private readonly InputAction m_InputUI_CloseInventory;
    private readonly InputAction m_InputUI_EButton;
    private readonly InputAction m_InputUI_LeftClickUI;
    private readonly InputAction m_InputUI_RightClickUI;
    private readonly InputAction m_InputUI_OpenMenuFromUI;
    public struct InputUIActions
    {
        private @InputActions m_Wrapper;
        public InputUIActions(@InputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @CloseInventory => m_Wrapper.m_InputUI_CloseInventory;
        public InputAction @EButton => m_Wrapper.m_InputUI_EButton;
        public InputAction @LeftClickUI => m_Wrapper.m_InputUI_LeftClickUI;
        public InputAction @RightClickUI => m_Wrapper.m_InputUI_RightClickUI;
        public InputAction @OpenMenuFromUI => m_Wrapper.m_InputUI_OpenMenuFromUI;
        public InputActionMap Get() { return m_Wrapper.m_InputUI; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(InputUIActions set) { return set.Get(); }
        public void SetCallbacks(IInputUIActions instance)
        {
            if (m_Wrapper.m_InputUIActionsCallbackInterface != null)
            {
                @CloseInventory.started -= m_Wrapper.m_InputUIActionsCallbackInterface.OnCloseInventory;
                @CloseInventory.performed -= m_Wrapper.m_InputUIActionsCallbackInterface.OnCloseInventory;
                @CloseInventory.canceled -= m_Wrapper.m_InputUIActionsCallbackInterface.OnCloseInventory;
                @EButton.started -= m_Wrapper.m_InputUIActionsCallbackInterface.OnEButton;
                @EButton.performed -= m_Wrapper.m_InputUIActionsCallbackInterface.OnEButton;
                @EButton.canceled -= m_Wrapper.m_InputUIActionsCallbackInterface.OnEButton;
                @LeftClickUI.started -= m_Wrapper.m_InputUIActionsCallbackInterface.OnLeftClickUI;
                @LeftClickUI.performed -= m_Wrapper.m_InputUIActionsCallbackInterface.OnLeftClickUI;
                @LeftClickUI.canceled -= m_Wrapper.m_InputUIActionsCallbackInterface.OnLeftClickUI;
                @RightClickUI.started -= m_Wrapper.m_InputUIActionsCallbackInterface.OnRightClickUI;
                @RightClickUI.performed -= m_Wrapper.m_InputUIActionsCallbackInterface.OnRightClickUI;
                @RightClickUI.canceled -= m_Wrapper.m_InputUIActionsCallbackInterface.OnRightClickUI;
                @OpenMenuFromUI.started -= m_Wrapper.m_InputUIActionsCallbackInterface.OnOpenMenuFromUI;
                @OpenMenuFromUI.performed -= m_Wrapper.m_InputUIActionsCallbackInterface.OnOpenMenuFromUI;
                @OpenMenuFromUI.canceled -= m_Wrapper.m_InputUIActionsCallbackInterface.OnOpenMenuFromUI;
            }
            m_Wrapper.m_InputUIActionsCallbackInterface = instance;
            if (instance != null)
            {
                @CloseInventory.started += instance.OnCloseInventory;
                @CloseInventory.performed += instance.OnCloseInventory;
                @CloseInventory.canceled += instance.OnCloseInventory;
                @EButton.started += instance.OnEButton;
                @EButton.performed += instance.OnEButton;
                @EButton.canceled += instance.OnEButton;
                @LeftClickUI.started += instance.OnLeftClickUI;
                @LeftClickUI.performed += instance.OnLeftClickUI;
                @LeftClickUI.canceled += instance.OnLeftClickUI;
                @RightClickUI.started += instance.OnRightClickUI;
                @RightClickUI.performed += instance.OnRightClickUI;
                @RightClickUI.canceled += instance.OnRightClickUI;
                @OpenMenuFromUI.started += instance.OnOpenMenuFromUI;
                @OpenMenuFromUI.performed += instance.OnOpenMenuFromUI;
                @OpenMenuFromUI.canceled += instance.OnOpenMenuFromUI;
            }
        }
    }
    public InputUIActions @InputUI => new InputUIActions(this);
    private int m_NewcontrolschemeSchemeIndex = -1;
    public InputControlScheme NewcontrolschemeScheme
    {
        get
        {
            if (m_NewcontrolschemeSchemeIndex == -1) m_NewcontrolschemeSchemeIndex = asset.FindControlSchemeIndex("New control scheme");
            return asset.controlSchemes[m_NewcontrolschemeSchemeIndex];
        }
    }
    public interface IInputPlayerActions
    {
        void OnPlayerMovement(InputAction.CallbackContext context);
        void OnPrimaryAction(InputAction.CallbackContext context);
        void OnSecondaryAction(InputAction.CallbackContext context);
        void OnHotbar1(InputAction.CallbackContext context);
        void OnHotbar2(InputAction.CallbackContext context);
        void OnHotbar3(InputAction.CallbackContext context);
        void OnHotbar4(InputAction.CallbackContext context);
        void OnHotbar5(InputAction.CallbackContext context);
        void OnHotbar6(InputAction.CallbackContext context);
        void OnHotbar7(InputAction.CallbackContext context);
        void OnHotbar8(InputAction.CallbackContext context);
        void OnInteract(InputAction.CallbackContext context);
        void OnOpenInventory(InputAction.CallbackContext context);
        void OnOpenMenuFromPlayer(InputAction.CallbackContext context);
    }
    public interface IInputMenuActions
    {
        void OnMenuMovement(InputAction.CallbackContext context);
        void OnLeftClickMenu(InputAction.CallbackContext context);
        void OnRightClickMenu(InputAction.CallbackContext context);
        void OnCloseMenu(InputAction.CallbackContext context);
    }
    public interface IInputUIActions
    {
        void OnCloseInventory(InputAction.CallbackContext context);
        void OnEButton(InputAction.CallbackContext context);
        void OnLeftClickUI(InputAction.CallbackContext context);
        void OnRightClickUI(InputAction.CallbackContext context);
        void OnOpenMenuFromUI(InputAction.CallbackContext context);
    }
}
